spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: "Naver"
            client-id: "dummy-naver-client-id"
            client-secret: "dummy-naver-client-secret"
            redirect-uri: "dumy"
            authorization-grant-type: "authorization_code"
            scope: "dummy"
          kakao:
            client-name: "Kakao"
            client-id: "dummy-kakao-client-id"
            client-secret: "dummy-kakao-client-secret"
            client-authentication-method: "post"
            redirect-uri: "dummy"
            authorization-grant-type: "authorization_code"
            scope: "dummy"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jwt:
    secret: UI4Tv+IPs8QP8Cu18EgE83vi5tk3YLTmDPplA3EeBQg=
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instance-name: TestScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.simpl.RAMJobStore
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 3
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  flyway:
    enabled: false
cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: test
    s3:
      bucket: test
    cloudfront:
      domain: https://test.cloudfront.net

payment:
  toss:
    client-key: test_ck_P9BRQmyarYleDvqAJl9vVJ07KzLN
    security-key: test_sk_ORzdMaqN3woDka0GDmGN35AkYXQG

logging:
  level:
    org.springframework.security: trace

client:
  url: "http://test"
