spring:
  jpa:
    hibernate:
      ddl-auto: create


payment:
  toss:
    client-key: test_ck_P9BRQmyarYleDvqAJl9vVJ07KzLN
    security-key: test_sk_ORzdMaqN3woDka0GDmGN35AkYXQG
logging:
  level:
    org.springframework.security: trace
