spring:
  jpa:
    hibernate:
      ddl-auto: create

cloud:
  aws:
    credentials:
      access-key: test-access-key
      secret-key: test-secret-key
    region:
      static: us-east-1
    s3:
      bucket: test-bucket

payment:
  toss:
    client-key: test
    security-key: test
logging:
  level:
    org.springframework.security: trace
