spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: test
    s3:
      bucket: test
    cloudfront:
      domain: https://test.cloudfront.net

payment:
  toss:
    client-key: test_ck_P9BRQmyarYleDvqAJl9vVJ07KzLN
    security-key: test_sk_ORzdMaqN3woDka0GDmGN35AkYXQG

logging:
  level:
    org.springframework.security: trace
