spring:
  jpa:
    hibernate:
      ddl-auto: create


payment:
  toss:
    client-key: ${TEST_CLIENT_KEY}
    security-key: ${TEST_SECRET_KEY}
logging:
  level:
    org.springframework.security: trace
