spring:
  jpa:
    hibernate:
      ddl-auto: create

cloud:
  aws:
    credentials:
      access-key: ${{secrets.S3_AWS_ACCESS_KEY_ID}}
      secret-key: ${{secrets.S3_AWS_SECRET_ACCESS_KEY}}
    region:
      static: ${{secrets.AWS_REGION}}
    s3:
      bucket: ${{secrets.AWS_S3_BUCKET}}
    cloudfront:
      domain: ${{secrets.AWS_CLOUDFRONT_DOMAIN}}

payment:
  toss:
    client-key: ${{secrets.TEST_CLIENT_KEY}}
    security-key: ${{secrets.TEST_SECRET_KEY}}
logging:
  level:
    org.springframework.security: trace
