spring:
  jpa:
    hibernate:
      ddl-auto: create


payment:
  toss:
    client-key: ${{secret.TEST_CLIENT_KEY}}
    security-key: ${{secret.TEST_SECRET_KEY}}
logging:
  level:
    org.springframework.security: trace
