spring:
  jpa:
    hibernate:
      ddl-auto: create

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
    cloudfront:
      domain: ${AWS_CLOUDFRONT_DOMAIN}

payment:
  toss:
    client-key: ${{secret.TEST_CLIENT_KEY}}
    security-key: ${{secret.TEST_SECRET_KEY}}
logging:
  level:
    org.springframework.security: trace
